name: WhateverAPI
version: A.2
main: com.bonkle.whatever.WhMain
api-version: 1.18
authors: [ Cak ]
load: STARTUP
description: Api for adding whatever!
commands:
  customitemmenu:
    description: Shows a menu of all custom items with WhateverAPI.
    usage: /customitemmenu
    aliases: [ cim ]